#!/bin/bash

DUP="$HOME/.duplicity"

# load gdrive settings file
export GOOGLE_DRIVE_SETTINGS=$DUP/credentials

# use GPG passphrase indicated on local filesystem
# run duplicity using include/exclude rules
env PASSPHRASE=$(cat $DUP/passphrase) \
    duplicity --include-filelist $DUP/include \
          --exclude-filelist $DUP/ignore \
          ~/ \
          $(cat $DUP/target) \
          -v 3 \
          "$@"
