#!/bin/bash

IGNORED_FILES_PATTERN='.*sw[klmnop]$'

# run_tests executes a single round of testing
run_tests () {
    clear
    echo "Installing..."
    if go install $@; then
        echo "Testing..."
        gotestsum $@ 
    fi
}

# run initial round of tests
run_tests

inotifywait --exclude="${IGNORED_FILES_PATTERN}" -e modify,moved_from -m -r -q . |
while read -r directory events filename; do
  # skip any events not on .go files
  if ! [[ "${filename}" =~ \.go$ ]] ; then
    continue
  fi

  # Because inotifywait generates lots of events, but we only
  # want to test once, we drain all of the events and timeout
  # after .1 seconds of no new events, then test:
  while read -t .1; do
      true
  done

  run_tests
done
