#!/usr/bin/env bash 

# Set parameters
delay='0.2'
uuid="$(uuidgen)"
windowid="$(xdotool getwindowfocus)"

# Execute insert
sleep "${delay}" && xdotool windowactivate --sync "${windowid}" type "${uuid}"
