#!/usr/bin/env bash 

# Set parameters
delay='0.2'
timestamp="$(date --utc '+%Y-%m-%dT%H:%M:%SZ')"
windowid="$(xdotool getwindowfocus)"

# Execute insert
sleep "${delay}" && xdotool windowactivate --sync "${windowid}" type "${timestamp}"
