#!/bin/bash

usage() {
  printf '%s\n' "Usage: maintain [-h] [-y]
Keep apt packages up-to-date.

where:
  -h, --help  - show this help text
  -y, --yes   - perform all steps w/o confirmation"
}

maintain() {
  local auto_accept="$1"

  if [[ "${auto_accept}" == 'true' ]]; then

    sudo apt update
    sudo apt upgrade -y
    sudo apt autoremove -y

  else 

    sudo apt update
    
    read -p 'List?'
    sudo apt list --upgradeable
   
    read -p 'Upgrade?'
    sudo apt upgrade
    
    read -p 'Autoremove?'
    sudo apt autoremove

    if [ -x purge-residual-config ] ; then
      read -p 'Purge residual config?'
      purge-residual-config
    fi
  fi
}

# Option parsing
declare PARAMS=""
declare AUTO_ACCEPT='false'
while (( "$#" )); do
  case "$1" in 
    -h|--help)  # display help message
      usage
      exit 1
      ;;
    -y|--yes)  # set autoaccept policy
      AUTO_ACCEPT='true'
      break
      ;;
    --)  # End argument parsing
      shift
      break
      ;;
    -*|--*)  # unsupported flags
      echo "Unsupported flag: $1" >&2
      usage
      exit 1
      ;;
    *)  # preserve positional arguments
      PARAMS="${PARAMS} maintain"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "${PARAMS}"

# Freeze configuration flags
readonly AUTO_ACCEPT

maintain "${AUTO_ACCEPT}"
