#!/bin/bash

# Grab color of top left pixel
color=$( convert "$1" -format "%[pixel:p{0,0}]" info:- )

# Make transparent instances of that color in the 'background'
convert "$1" -alpha off -bordercolor $color -border 1 \
    \( +clone -fuzz 30% -fill none -floodfill +0+0 $color \
       -alpha extract -geometry 200% -blur 0x0.5 \
       -morphology erode square:1 -geometry 50% \) \
    -compose CopyOpacity -composite -shave 1 "$2"

# Make transparent instances of that color throughout
# convert "$1" -fuzz 30% -transparent "$color" "$2"
