#!/bin/bash


if [[ -z "$1" ]] ; then
	echo "Usage: pizzapi protocol [user]"
	exit 1
elif [[ -z "$2" ]] ; then
	username="$USER"
else
	username="$2"
fi

protocol="$1"
port=7777

case $protocol in
	ssh)
		ssh -p $port $username@$CLARK_HOST
		;;
	sftp)
		sftp -P $port $username@$CLARK_HOST
		;;
esac

